# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MenuPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WIndow_Aquazul(object):
    def setupUi(self, WIndow_Aquazul):
        WIndow_Aquazul.setObjectName("WIndow_Aquazul")
        WIndow_Aquazul.resize(1060, 820)
        WIndow_Aquazul.setMinimumSize(QtCore.QSize(1060, 820))
        WIndow_Aquazul.setMaximumSize(QtCore.QSize(1060, 828))
        WIndow_Aquazul.setStyleSheet("border: 2px solid #3498db;\n"
"border-radius: 10px;\n"
"padding: 20px;\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.centralwidget = QtWidgets.QWidget(WIndow_Aquazul)
        self.centralwidget.setStyleSheet("background-color: #f2f2f2;\n"
"border-radius: 10px;\n"
"padding: 20px;\n"
"color: #333333;\n"
"font-size: 16px;\n"
"font-family: Arial, sans-serif;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(226, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.lbl_title = QtWidgets.QLabel(self.frame_2)
        self.lbl_title.setMinimumSize(QtCore.QSize(500, 50))
        self.lbl_title.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lbl_title.setStyleSheet("background-color: #eaf2ff;\n"
"border: 2px solid #3498db;\n"
"border-radius: 8px;\n"
"padding: 10px;\n"
"color: #333333;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"text-align: center;")
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.horizontalLayout_6.addWidget(self.lbl_title)
        spacerItem1 = QtWidgets.QSpacerItem(225, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.name_user = QtWidgets.QLabel(self.frame_2)
        self.name_user.setMinimumSize(QtCore.QSize(360, 50))
        self.name_user.setMaximumSize(QtCore.QSize(360, 60))
        self.name_user.setStyleSheet("background-color: #eaf2ff;\n"
"border: 2px solid #3498db;\n"
"border-radius: 8px;\n"
"padding: 10px;\n"
"color: #333333;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"text-align: center;")
        self.name_user.setObjectName("name_user")
        self.horizontalLayout_6.addWidget(self.name_user)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.frame_3.setStyleSheet("background-color: #eaf2ff;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setMinimumSize(QtCore.QSize(0, 210))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 240))
        self.frame.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_habitat = QtWidgets.QPushButton(self.frame)
        self.btn_habitat.setGeometry(QtCore.QRect(524, 33, 150, 144))
        self.btn_habitat.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_habitat.setMaximumSize(QtCore.QSize(150, 150))
        self.btn_habitat.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_habitat.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.btn_habitat.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Images/MainWindow/habitat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_habitat.setIcon(icon)
        self.btn_habitat.setIconSize(QtCore.QSize(300, 200))
        self.btn_habitat.setObjectName("btn_habitat")
        self.btn_animal = QtWidgets.QPushButton(self.frame)
        self.btn_animal.setGeometry(QtCore.QRect(92, 33, 150, 144))
        self.btn_animal.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_animal.setMaximumSize(QtCore.QSize(150, 150))
        self.btn_animal.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_animal.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.btn_animal.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Images/MainWindow/animal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_animal.setIcon(icon1)
        self.btn_animal.setIconSize(QtCore.QSize(300, 200))
        self.btn_animal.setObjectName("btn_animal")
        self.btn_especie = QtWidgets.QPushButton(self.frame)
        self.btn_especie.setGeometry(QtCore.QRect(308, 33, 150, 144))
        self.btn_especie.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_especie.setMaximumSize(QtCore.QSize(150, 150))
        self.btn_especie.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_especie.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.btn_especie.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Images/MainWindow/especie.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_especie.setIcon(icon2)
        self.btn_especie.setIconSize(QtCore.QSize(300, 200))
        self.btn_especie.setObjectName("btn_especie")
        self.btn_peligro = QtWidgets.QPushButton(self.frame)
        self.btn_peligro.setGeometry(QtCore.QRect(740, 33, 150, 144))
        self.btn_peligro.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_peligro.setMaximumSize(QtCore.QSize(150, 150))
        self.btn_peligro.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_peligro.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.btn_peligro.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../Images/MainWindow/peligro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_peligro.setIcon(icon3)
        self.btn_peligro.setIconSize(QtCore.QSize(300, 200))
        self.btn_peligro.setObjectName("btn_peligro")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(80, 180, 151, 21))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(300, 180, 151, 21))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(520, 180, 151, 21))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(740, 180, 151, 21))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 210))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 240))
        self.frame_4.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.btn_empleado = QtWidgets.QPushButton(self.frame_4)
        self.btn_empleado.setGeometry(QtCore.QRect(524, 33, 150, 144))
        self.btn_empleado.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_empleado.setMaximumSize(QtCore.QSize(150, 150))
        self.btn_empleado.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.btn_empleado.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../Images/MainWindow/empleados.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_empleado.setIcon(icon4)
        self.btn_empleado.setIconSize(QtCore.QSize(150, 150))
        self.btn_empleado.setObjectName("btn_empleado")
        self.btn_correo = QtWidgets.QPushButton(self.frame_4)
        self.btn_correo.setGeometry(QtCore.QRect(740, 33, 150, 144))
        self.btn_correo.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_correo.setMaximumSize(QtCore.QSize(150, 150))
        self.btn_correo.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.btn_correo.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../Images/MainWindow/correo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_correo.setIcon(icon5)
        self.btn_correo.setIconSize(QtCore.QSize(150, 150))
        self.btn_correo.setObjectName("btn_correo")
        self.btn_alimentacion = QtWidgets.QPushButton(self.frame_4)
        self.btn_alimentacion.setGeometry(QtCore.QRect(308, 33, 150, 144))
        self.btn_alimentacion.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_alimentacion.setMaximumSize(QtCore.QSize(150, 150))
        self.btn_alimentacion.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.btn_alimentacion.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../Images/MainWindow/alimento.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_alimentacion.setIcon(icon6)
        self.btn_alimentacion.setIconSize(QtCore.QSize(150, 150))
        self.btn_alimentacion.setObjectName("btn_alimentacion")
        self.btn_material = QtWidgets.QPushButton(self.frame_4)
        self.btn_material.setGeometry(QtCore.QRect(92, 33, 150, 144))
        self.btn_material.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_material.setMaximumSize(QtCore.QSize(150, 150))
        self.btn_material.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.btn_material.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../Images/MainWindow/material.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_material.setIcon(icon7)
        self.btn_material.setIconSize(QtCore.QSize(150, 200))
        self.btn_material.setObjectName("btn_material")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(90, 180, 151, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(310, 180, 151, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(520, 180, 151, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(730, 180, 151, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 210))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 240))
        self.frame_5.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.btn_sucursal = QtWidgets.QPushButton(self.frame_5)
        self.btn_sucursal.setGeometry(QtCore.QRect(92, 33, 150, 144))
        self.btn_sucursal.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_sucursal.setMaximumSize(QtCore.QSize(150, 150))
        self.btn_sucursal.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.btn_sucursal.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../Images/MainWindow/sucursal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_sucursal.setIcon(icon8)
        self.btn_sucursal.setIconSize(QtCore.QSize(150, 150))
        self.btn_sucursal.setObjectName("btn_sucursal")
        self.btn_estado = QtWidgets.QPushButton(self.frame_5)
        self.btn_estado.setGeometry(QtCore.QRect(308, 33, 150, 144))
        self.btn_estado.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_estado.setMaximumSize(QtCore.QSize(150, 150))
        self.btn_estado.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.btn_estado.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../Images/MainWindow/mexico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_estado.setIcon(icon9)
        self.btn_estado.setIconSize(QtCore.QSize(150, 150))
        self.btn_estado.setObjectName("btn_estado")
        self.btn_direccion = QtWidgets.QPushButton(self.frame_5)
        self.btn_direccion.setGeometry(QtCore.QRect(524, 33, 150, 144))
        self.btn_direccion.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_direccion.setMaximumSize(QtCore.QSize(150, 150))
        self.btn_direccion.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.btn_direccion.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../Images/MainWindow/direccion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_direccion.setIcon(icon10)
        self.btn_direccion.setIconSize(QtCore.QSize(150, 150))
        self.btn_direccion.setObjectName("btn_direccion")
        self.btn_tipoagua = QtWidgets.QPushButton(self.frame_5)
        self.btn_tipoagua.setGeometry(QtCore.QRect(740, 33, 150, 144))
        self.btn_tipoagua.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_tipoagua.setMaximumSize(QtCore.QSize(150, 150))
        self.btn_tipoagua.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: white;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.btn_tipoagua.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../Images/MainWindow/tipo_agua.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_tipoagua.setIcon(icon11)
        self.btn_tipoagua.setIconSize(QtCore.QSize(150, 150))
        self.btn_tipoagua.setObjectName("btn_tipoagua")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(310, 180, 151, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(520, 180, 151, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(740, 180, 151, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(90, 180, 151, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_3)
        WIndow_Aquazul.setCentralWidget(self.centralwidget)

        self.retranslateUi(WIndow_Aquazul)
        QtCore.QMetaObject.connectSlotsByName(WIndow_Aquazul)

    def retranslateUi(self, WIndow_Aquazul):
        _translate = QtCore.QCoreApplication.translate
        WIndow_Aquazul.setWindowTitle(_translate("WIndow_Aquazul", "Menu Principal"))
        self.lbl_title.setText(_translate("WIndow_Aquazul", "AQUAZUL - ACUARIO "))
        self.name_user.setText(_translate("WIndow_Aquazul", "usuario"))
        self.label_9.setText(_translate("WIndow_Aquazul", "Animal"))
        self.label_10.setText(_translate("WIndow_Aquazul", "Especie"))
        self.label_11.setText(_translate("WIndow_Aquazul", "Habitat"))
        self.label_12.setText(_translate("WIndow_Aquazul", "Peligro"))
        self.label_5.setText(_translate("WIndow_Aquazul", "Material"))
        self.label_6.setText(_translate("WIndow_Aquazul", "Alimentación"))
        self.label_7.setText(_translate("WIndow_Aquazul", "Empleado"))
        self.label_8.setText(_translate("WIndow_Aquazul", "Correo"))
        self.label.setText(_translate("WIndow_Aquazul", "Estado"))
        self.label_2.setText(_translate("WIndow_Aquazul", "Dirección"))
        self.label_3.setText(_translate("WIndow_Aquazul", "Tipo de agua"))
        self.label_4.setText(_translate("WIndow_Aquazul", "Sucursal"))
