# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Animal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnimalScreen(object):
    def setupUi(self, AnimalScreen):
        AnimalScreen.setObjectName("AnimalScreen")
        AnimalScreen.resize(568, 600)
        AnimalScreen.setMinimumSize(QtCore.QSize(568, 600))
        AnimalScreen.setMaximumSize(QtCore.QSize(568, 600))
        AnimalScreen.setStyleSheet("border: 2px solid #3498db;\n"
"border-radius: 10px;\n"
"\n"
"background-color: #eaf2ff;")
        self.centralwidget = QtWidgets.QWidget(AnimalScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(550, 250))
        self.groupBox.setMaximumSize(QtCore.QSize(551, 251))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color:#eaf2ff;")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 40, 131, 21))
        self.label.setStyleSheet("background-color: #eaf2ff;\n"
"border: 2px solid #3498db;\n"
"border-radius: 8px;\n"
"color: #333333;\n"
"font-size: 11px;\n"
"font-weight: bold;\n"
"text-align: center;")
        self.label.setObjectName("label")
        self.line_nombre = QtWidgets.QLineEdit(self.groupBox)
        self.line_nombre.setGeometry(QtCore.QRect(150, 40, 121, 20))
        self.line_nombre.setObjectName("line_nombre")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 131, 21))
        self.label_2.setStyleSheet("background-color: #eaf2ff;\n"
"border: 2px solid #3498db;\n"
"border-radius: 8px;\n"
"color: #333333;\n"
"font-size: 10px;\n"
"font-weight: bold;\n"
"text-align: center;")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.line_cantAli = QtWidgets.QLineEdit(self.groupBox)
        self.line_cantAli.setGeometry(QtCore.QRect(150, 70, 121, 20))
        self.line_cantAli.setObjectName("line_cantAli")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 131, 21))
        self.label_3.setStyleSheet("background-color: #eaf2ff;\n"
"border: 2px solid #3498db;\n"
"border-radius: 8px;\n"
"color: #333333;\n"
"font-size: 10px;\n"
"font-weight: bold;\n"
"text-align: center;")
        self.label_3.setObjectName("label_3")
        self.line_condicion = QtWidgets.QLineEdit(self.groupBox)
        self.line_condicion.setGeometry(QtCore.QRect(150, 100, 121, 20))
        self.line_condicion.setObjectName("line_condicion")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 121, 21))
        self.label_4.setStyleSheet("background-color: #eaf2ff;\n"
"border: 2px solid #3498db;\n"
"border-radius: 8px;\n"
"color: #333333;\n"
"font-size: 10px;\n"
"font-weight: bold;\n"
"text-align: center;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 121, 21))
        self.label_5.setStyleSheet("background-color: #eaf2ff;\n"
"border: 2px solid #3498db;\n"
"border-radius: 8px;\n"
"color: #333333;\n"
"font-size: 10px;\n"
"font-weight: bold;\n"
"text-align: center;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 210, 121, 21))
        self.label_6.setStyleSheet("background-color: #eaf2ff;\n"
"border: 2px solid #3498db;\n"
"border-radius: 8px;\n"
"color: #333333;\n"
"font-size: 10px;\n"
"font-weight: bold;\n"
"text-align: center;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(290, 40, 91, 21))
        self.label_7.setStyleSheet("background-color: #eaf2ff;\n"
"border: 2px solid #3498db;\n"
"border-radius: 8px;\n"
"color: #333333;\n"
"font-size: 10px;\n"
"font-weight: bold;\n"
"text-align: center;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(290, 70, 91, 21))
        self.label_8.setStyleSheet("background-color: #eaf2ff;\n"
"border: 2px solid #3498db;\n"
"border-radius: 8px;\n"
"color: #333333;\n"
"font-size: 10px;\n"
"font-weight: bold;\n"
"text-align: center;")
        self.label_8.setObjectName("label_8")
        self.btn_especie = QtWidgets.QPushButton(self.groupBox)
        self.btn_especie.setGeometry(QtCore.QRect(320, 140, 60, 60))
        self.btn_especie.setMinimumSize(QtCore.QSize(55, 55))
        self.btn_especie.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_especie.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_especie.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: black;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.btn_especie.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Images/Botones Interfaz/agregar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_especie.setIcon(icon)
        self.btn_especie.setIconSize(QtCore.QSize(50, 50))
        self.btn_especie.setObjectName("btn_especie")
        self.btn_especie_2 = QtWidgets.QPushButton(self.groupBox)
        self.btn_especie_2.setGeometry(QtCore.QRect(390, 140, 60, 60))
        self.btn_especie_2.setMinimumSize(QtCore.QSize(55, 55))
        self.btn_especie_2.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_especie_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_especie_2.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: black;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.btn_especie_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Images/Botones Interfaz/editar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_especie_2.setIcon(icon1)
        self.btn_especie_2.setIconSize(QtCore.QSize(50, 50))
        self.btn_especie_2.setObjectName("btn_especie_2")
        self.btn_especie_3 = QtWidgets.QPushButton(self.groupBox)
        self.btn_especie_3.setGeometry(QtCore.QRect(460, 140, 60, 60))
        self.btn_especie_3.setMinimumSize(QtCore.QSize(55, 55))
        self.btn_especie_3.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_especie_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_especie_3.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: black;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.btn_especie_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../Images/Botones Interfaz/borrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_especie_3.setIcon(icon2)
        self.btn_especie_3.setIconSize(QtCore.QSize(50, 50))
        self.btn_especie_3.setObjectName("btn_especie_3")
        self.line_especie = QtWidgets.QLineEdit(self.groupBox)
        self.line_especie.setGeometry(QtCore.QRect(390, 40, 121, 20))
        self.line_especie.setObjectName("line_especie")
        self.line_sucursal = QtWidgets.QLineEdit(self.groupBox)
        self.line_sucursal.setGeometry(QtCore.QRect(390, 70, 121, 20))
        self.line_sucursal.setObjectName("line_sucursal")
        self.line_alimentacion = QtWidgets.QLineEdit(self.groupBox)
        self.line_alimentacion.setGeometry(QtCore.QRect(150, 150, 121, 20))
        self.line_alimentacion.setObjectName("line_alimentacion")
        self.line_peligro = QtWidgets.QLineEdit(self.groupBox)
        self.line_peligro.setGeometry(QtCore.QRect(150, 180, 121, 20))
        self.line_peligro.setObjectName("line_peligro")
        self.line_habitat = QtWidgets.QLineEdit(self.groupBox)
        self.line_habitat.setGeometry(QtCore.QRect(150, 210, 121, 20))
        self.line_habitat.setObjectName("line_habitat")
        self.verticalLayout.addWidget(self.groupBox)
        self.asda = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.asda.setFont(font)
        self.asda.setStyleSheet("background-color: #eaf2ff;\n"
"padding: 12px;\n"
"\n"
"")
        self.asda.setObjectName("asda")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.asda)
        self.horizontalLayout.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table_animal = QtWidgets.QTableWidget(self.asda)
        self.table_animal.setObjectName("table_animal")
        self.table_animal.setColumnCount(0)
        self.table_animal.setRowCount(0)
        self.horizontalLayout.addWidget(self.table_animal)
        self.verticalLayout.addWidget(self.asda)
        AnimalScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(AnimalScreen)
        QtCore.QMetaObject.connectSlotsByName(AnimalScreen)

    def retranslateUi(self, AnimalScreen):
        _translate = QtCore.QCoreApplication.translate
        AnimalScreen.setWindowTitle(_translate("AnimalScreen", "Animal"))
        self.groupBox.setTitle(_translate("AnimalScreen", "Animal"))
        self.label.setText(_translate("AnimalScreen", "Nombre:"))
        self.label_2.setText(_translate("AnimalScreen", "Cantidad de alimento:"))
        self.label_3.setText(_translate("AnimalScreen", "Condicion:"))
        self.label_4.setText(_translate("AnimalScreen", "Tipo de alimentacion:"))
        self.label_5.setText(_translate("AnimalScreen", "Peligro de extincion:"))
        self.label_6.setText(_translate("AnimalScreen", "Habitat:"))
        self.label_7.setText(_translate("AnimalScreen", "Especie:"))
        self.label_8.setText(_translate("AnimalScreen", "Sucursal:"))
        self.asda.setTitle(_translate("AnimalScreen", "Mostrar"))
