# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sucursal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SucursalScreen(object):
    def setupUi(self, SucursalScreen):
        SucursalScreen.setObjectName("SucursalScreen")
        SucursalScreen.resize(568, 600)
        SucursalScreen.setMinimumSize(QtCore.QSize(568, 600))
        SucursalScreen.setMaximumSize(QtCore.QSize(568, 600))
        SucursalScreen.setStyleSheet("border: 2px solid #3498db;\n"
"border-radius: 10px;\n"
"\n"
"background-color: #eaf2ff;")
        self.centralwidget = QtWidgets.QWidget(SucursalScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(550, 250))
        self.groupBox.setMaximumSize(QtCore.QSize(551, 250))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color:#eaf2ff;")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 40, 111, 21))
        self.label.setStyleSheet("background-color: #eaf2ff;\n"
"border: 2px solid #3498db;\n"
"border-radius: 8px;\n"
"color: #333333;\n"
"font-size: 11px;\n"
"font-weight: bold;\n"
"text-align: center;")
        self.label.setObjectName("label")
        self.line_sucursal = QtWidgets.QLineEdit(self.groupBox)
        self.line_sucursal.setGeometry(QtCore.QRect(130, 40, 161, 20))
        self.line_sucursal.setObjectName("line_sucursal")
        self.btn_agregar = QtWidgets.QPushButton(self.groupBox)
        self.btn_agregar.setGeometry(QtCore.QRect(310, 130, 60, 60))
        self.btn_agregar.setMinimumSize(QtCore.QSize(55, 55))
        self.btn_agregar.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_agregar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_agregar.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: black;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.btn_agregar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Images/Botones Interfaz/agregar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_agregar.setIcon(icon)
        self.btn_agregar.setIconSize(QtCore.QSize(50, 50))
        self.btn_agregar.setObjectName("btn_agregar")
        self.btn_editar = QtWidgets.QPushButton(self.groupBox)
        self.btn_editar.setGeometry(QtCore.QRect(380, 130, 60, 60))
        self.btn_editar.setMinimumSize(QtCore.QSize(55, 55))
        self.btn_editar.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_editar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_editar.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: black;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.btn_editar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Images/Botones Interfaz/editar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_editar.setIcon(icon1)
        self.btn_editar.setIconSize(QtCore.QSize(50, 50))
        self.btn_editar.setObjectName("btn_editar")
        self.btn_borrar = QtWidgets.QPushButton(self.groupBox)
        self.btn_borrar.setGeometry(QtCore.QRect(450, 130, 60, 60))
        self.btn_borrar.setMinimumSize(QtCore.QSize(55, 55))
        self.btn_borrar.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_borrar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_borrar.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: black;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.btn_borrar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../Images/Botones Interfaz/borrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_borrar.setIcon(icon2)
        self.btn_borrar.setIconSize(QtCore.QSize(50, 50))
        self.btn_borrar.setObjectName("btn_borrar")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 111, 21))
        self.label_2.setStyleSheet("background-color: #eaf2ff;\n"
"border: 2px solid #3498db;\n"
"border-radius: 8px;\n"
"color: #333333;\n"
"font-size: 11px;\n"
"font-weight: bold;\n"
"text-align: center;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.label_3.setStyleSheet("background-color: #eaf2ff;\n"
"border: 2px solid #3498db;\n"
"border-radius: 8px;\n"
"color: #333333;\n"
"font-size: 11px;\n"
"font-weight: bold;\n"
"text-align: center;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 111, 21))
        self.label_4.setStyleSheet("background-color: #eaf2ff;\n"
"border: 2px solid #3498db;\n"
"border-radius: 8px;\n"
"color: #333333;\n"
"font-size: 11px;\n"
"font-weight: bold;\n"
"text-align: center;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 111, 21))
        self.label_5.setStyleSheet("background-color: #eaf2ff;\n"
"border: 2px solid #3498db;\n"
"border-radius: 8px;\n"
"color: #333333;\n"
"font-size: 11px;\n"
"font-weight: bold;\n"
"text-align: center;")
        self.label_5.setObjectName("label_5")
        self.line_lada = QtWidgets.QLineEdit(self.groupBox)
        self.line_lada.setGeometry(QtCore.QRect(130, 70, 161, 20))
        self.line_lada.setObjectName("line_lada")
        self.line_telefono = QtWidgets.QLineEdit(self.groupBox)
        self.line_telefono.setGeometry(QtCore.QRect(130, 100, 161, 20))
        self.line_telefono.setObjectName("line_telefono")
        self.line_extension = QtWidgets.QLineEdit(self.groupBox)
        self.line_extension.setGeometry(QtCore.QRect(130, 130, 161, 20))
        self.line_extension.setObjectName("line_extension")
        self.line_paginaweb = QtWidgets.QLineEdit(self.groupBox)
        self.line_paginaweb.setGeometry(QtCore.QRect(130, 160, 161, 20))
        self.line_paginaweb.setObjectName("line_paginaweb")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(310, 40, 91, 21))
        self.label_7.setStyleSheet("background-color: #eaf2ff;\n"
"border: 2px solid #3498db;\n"
"border-radius: 8px;\n"
"color: #333333;\n"
"font-size: 10px;\n"
"font-weight: bold;\n"
"text-align: center;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(310, 70, 91, 21))
        self.label_8.setStyleSheet("background-color: #eaf2ff;\n"
"border: 2px solid #3498db;\n"
"border-radius: 8px;\n"
"color: #333333;\n"
"font-size: 10px;\n"
"font-weight: bold;\n"
"text-align: center;")
        self.label_8.setObjectName("label_8")
        self.line_direccion = QtWidgets.QLineEdit(self.groupBox)
        self.line_direccion.setGeometry(QtCore.QRect(410, 40, 121, 20))
        self.line_direccion.setObjectName("line_direccion")
        self.line_correo = QtWidgets.QLineEdit(self.groupBox)
        self.line_correo.setGeometry(QtCore.QRect(410, 70, 121, 20))
        self.line_correo.setObjectName("line_correo")
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("background-color: #eaf2ff;\n"
"padding: 12px;\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table_sucursal = QtWidgets.QTableWidget(self.groupBox_2)
        self.table_sucursal.setObjectName("table_sucursal")
        self.table_sucursal.setColumnCount(0)
        self.table_sucursal.setRowCount(0)
        self.horizontalLayout.addWidget(self.table_sucursal)
        self.verticalLayout.addWidget(self.groupBox_2)
        SucursalScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SucursalScreen)
        QtCore.QMetaObject.connectSlotsByName(SucursalScreen)

    def retranslateUi(self, SucursalScreen):
        _translate = QtCore.QCoreApplication.translate
        SucursalScreen.setWindowTitle(_translate("SucursalScreen", "Sucursal"))
        self.groupBox.setTitle(_translate("SucursalScreen", "Sucursal"))
        self.label.setText(_translate("SucursalScreen", "Nombre Sucursal"))
        self.label_2.setText(_translate("SucursalScreen", "Lada"))
        self.label_3.setText(_translate("SucursalScreen", "Telefono"))
        self.label_4.setText(_translate("SucursalScreen", "Extension"))
        self.label_5.setText(_translate("SucursalScreen", "Pagina Web"))
        self.label_7.setText(_translate("SucursalScreen", "Direccion"))
        self.label_8.setText(_translate("SucursalScreen", "Correo"))
        self.groupBox_2.setTitle(_translate("SucursalScreen", "Mostrar"))
