# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from GUI.LogIn import recursos_rc


class Ui_LogIn(object):
    def setupUi(self, LogIn):
        LogIn.setObjectName("LogIn")
        LogIn.resize(480, 360)
        font = QtGui.QFont()
        font.setPointSize(12)
        LogIn.setFont(font)
        LogIn.setStyleSheet("")
        self.lineEditUser = QtWidgets.QLineEdit(LogIn)
        self.lineEditUser.setGeometry(QtCore.QRect(170, 70, 200, 30))
        self.lineEditUser.setObjectName("lineEditUser")
        self.lineEditUser.setPlaceholderText('Usuario')
        self.lineEditPassword = QtWidgets.QLineEdit(LogIn)
        self.lineEditPassword.setGeometry(QtCore.QRect(170, 140, 200, 30))
        self.lineEditPassword.setText("")
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setPlaceholderText('Contraseña')
        self.pushButtonAccept = QtWidgets.QPushButton(LogIn)
        self.pushButtonAccept.setGeometry(QtCore.QRect(170, 260, 140, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButtonAccept.setFont(font)
        self.pushButtonAccept.setObjectName("pushButtonAccept")
        self.labelUser = QtWidgets.QLabel(LogIn)
        self.labelUser.setGeometry(QtCore.QRect(110, 60, 40, 40))
        self.labelUser.setStyleSheet("border-image: url(:/Images/user.png);")
        self.labelUser.setObjectName("labelUser")
        self.labelPassword = QtWidgets.QLabel(LogIn)
        self.labelPassword.setGeometry(QtCore.QRect(110, 130, 40, 40))
        self.labelPassword.setStyleSheet("border-image: url(:/Images/lock.png);")
        self.labelPassword.setText("")
        self.labelPassword.setObjectName("labelPassword")

        self.retranslateUi(LogIn)
        QtCore.QMetaObject.connectSlotsByName(LogIn)

    def retranslateUi(self, LogIn):
        _translate = QtCore.QCoreApplication.translate
        LogIn.setWindowTitle(_translate("LogIn", "Log In Acuazul"))
        self.pushButtonAccept.setText(_translate("LogIn", "Iniciar sesión"))
        self.labelUser.setText(_translate("LogIn", "<html><head/><body><p><br/></p></body></html>"))
